apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
  labels:
    app: my-mariadb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-mariadb
  template:
    metadata:
      labels:
        app: my-mariadb
    spec:
      volumes:
        - name: init-volume
          configMap:
            name: mariadb-deployment-init-configmap
      containers:
        - name: my-mariadb
          image: mariadb
          volumeMounts:
            - name: init-volume
              mountPath: /docker-entrypoint-initdb.d/
          env:
            - name: MARIADB_DATABASE
              value: "user_posts"
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: root-password
          ports:
            - containerPort: 3306
